/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#fe9d11",
        "inverse-surface": "#392e26",
        "on-tertiary-container": "#002e4f",
        "tertiary-container": "#0099f4",
        "on-primary-container": "#482200",
        "background-base": "#bfb5a3",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "surface-container-high": "#f8e4d8",
        "on-primary-fixed": "#2f1500",
        "surface": "#fff8f5",
        "outline": "#897363",
        "window-control-white": "#ffffff",
        "surface-panel": "#d4cabb",
        "on-secondary": "#ffffff",
        "primary": "#924c00",
        "inverse-on-surface": "#ffede3",
        "on-tertiary": "#ffffff",
        "surface-variant": "#f2dfd3",
        "surface-container-highest": "#f2dfd3",
        "surface-dim": "#ead6cb",
        "text-main": "#1a1a1a",
        "tertiary": "#00629f",
        "surface-container": "#feeade",
        "on-background": "#231a12",
        "surface-container-low": "#fff1e9",
        "tertiary-fixed-dim": "#9acbff",
        "secondary-fixed": "#ffdcbc",
        "on-primary-fixed-variant": "#6f3800",
        "on-tertiary-fixed-variant": "#004a79",
        "on-error-container": "#93000a",
        "on-surface-variant": "#564335",
        "status-error": "#d44a4a",
        "on-tertiary-fixed": "#001d34",
        "on-surface": "#231a12",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#d0e4ff",
        "on-secondary-container": "#663b00",
        "outline-variant": "#dcc1af",
        "secondary": "#895100",
        "primary-fixed-dim": "#ffb77f",
        "status-success": "#7fd44a",
        "secondary-fixed-dim": "#ffb86c",
        "on-secondary-fixed-variant": "#683d00",
        "surface-tint": "#924c00",
        "on-secondary-fixed": "#2c1700",
        "primary-container": "#e07800",
        "on-error": "#ffffff",
        "primary-fixed": "#ffdcc4",
        "inverse-primary": "#ffb77f",
        "background": "#fff8f5",
        "surface-bright": "#fff8f5"
      },
      spacing: {
        "unit": "4px",
        "shadow-offset": "3px",
        "margin-page": "16px",
        "gutter-grid": "12px",
        "border-width": "2px",
        "padding-card": "12px"
      },
      fontFamily: {
        "headline-md": ["JetBrains Mono", "monospace"],
        "body-md": ["JetBrains Mono", "monospace"],
        "title-bar": ["JetBrains Mono", "monospace"],
        "headline-lg": ["JetBrains Mono", "monospace"],
        "mono-code": ["JetBrains Mono", "monospace"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "body-lg": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "title-bar": ["16px", { lineHeight: "24px", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "mono-code": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
