import { precacheAndRoute } from 'workbox-precaching';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Handle Share Target POST request
self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);
  
  if (event.request.method === 'POST' && url.pathname === '/share') {
    event.respondWith(
      (async () => {
        try {
          const formData = await event.request.formData();
          const title = formData.get('title') || '';
          const text = formData.get('text') || '';
          const sharedUrl = formData.get('url') || '';
          
          // Construct GET URL redirect
          const targetUrl = new URL('/share', self.location.origin);
          if (title) targetUrl.searchParams.set('title', title);
          if (text) targetUrl.searchParams.set('text', text);
          if (sharedUrl) targetUrl.searchParams.set('url', sharedUrl);
          
          // Redirect to GET request on /share with query params
          return Response.redirect(targetUrl.href, 303);
        } catch (err) {
          console.error('[SW] Share target processing failed:', err);
          // Fallback redirect to home if form parsing fails
          return Response.redirect('/', 303);
        }
      })()
    );
  }
});
